spring.application.name=assignment

# H2 Database
spring.datasource.url=jdbc:h2:mem:forecastdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=kanishka
spring.datasource.password=kanishka@321

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Open Meteo
openmeteo.base-url=https://api.open-meteo.com